### ISSUE TITLE
Consider adding ~/.config/gaze.yaml as config path

### ISSUE THREAD

**Issue by tankorsmash** [wtetsu/gaze#2]
On linux there's either `~/.config/` or `~/config/` as a folder for everyone to put their dotfiles in, to keep the home dir from getting cluttered.

**Comment by wtetsu** [comment]
@tankorsmash 

Thank you, looks a good idea.
I'll deal with it.

**Comment by wtetsu** [comment]
Fix in [v1.1.1](https://github.com/wtetsu/gaze/releases/tag/v1.1.1)

**Comment by tankorsmash** [comment]
Thank you!
