### ISSUE TITLE
Does not appear to work on WSL?

### ISSUE THREAD

**Issue by rinfz** [wtetsu/gaze#3]
I can call gaze with no args and it prints the help message but when I try and run it against file(s) it doesn't seem to do anything at all.

**Comment by wtetsu** [comment]
@rinfz 

Hi, thank you for your report.

There was a problem when specifying current directory files on WSL.
[v0.1.7](https://github.com/wtetsu/gaze/releases/tag/v0.1.7) fixed it so please try it out.

```
wget https://github.com/wtetsu/gaze/releases/download/v0.1.7/gaze_linux_v0.1.7.zip
unzip gaze_linux_v0.1.7.zip   
cd gaze_linux_v0.1.7
chmod +x gaze
```

![gggg](https://user-images.githubusercontent.com/515948/88666056-817c8e00-d11a-11ea-865a-7a9f3bc5eda0.gif)

**Comment by rinfz** [comment]
It is working for me now, thanks!

**Comment by rinfz** [comment]
Just to note: this works in the fs of WSL but does not seem to work if you're gazing files on the  windows host (i.e. `/mnt/c/Users/.../`)

**Comment by wtetsu** [comment]
For me, Gaze worked on both `/tmp/..` and `/mnt/c/src/...`.
That's strange...?

**Comment by rinfz** [comment]
Ah yes, it appears to have been a temporary error, `/mnt` is working for me too now.
