### ISSUE TITLE
Missing release 1.1.1a

### ISSUE THREAD

**Issue by gromgit** [wtetsu/gaze#6]
Hi! I help out with the [Homebrew](https://brew.sh) project when I can, and I just noticed that there was a `gaze 1.1.1a` release, for which [we updated our formula and bottled new binaries on Aug 14 2022](https://github.com/Homebrew/homebrew-core/pull/108012).

However, I can't find that release anywhere in your project now. Was it accidentally released, and then removed? If so, are there any changes in that release, that distributors like us need to be aware of?

Thanks much!

**Comment by wtetsu** [comment]
Oh, that version was for testing purposes, but I was not aware of activity on your side.
Now I have released v1.1.2, may I ask you to work on updating the Homebrew side?

From now on, I will not carelessly delete releases.

**Comment by gromgit** [comment]
No worries, I've initiated a PR to update to 1.1.2: https://github.com/Homebrew/homebrew-core/pull/111590.
