### ISSUE TITLE
Seeing double :eye: :eye:

### ISSUE THREAD

**Issue by j-mnr** [wtetsu/gaze#8]
## Hello there fellow gopher :wave: :grin:

Great tool, trying it out in place of `entr` which I feel has a cumbersome CLI.

When I'm write a file with the command `gaze -c 'go test' example_test.go` I get my output double to the console. Meaning the tests run once and then run immediately again.

![image](https://user-images.githubusercontent.com/93833532/196806532-9cde79c8-d257-4432-ab55-9cf5d8278de7.png)

You can see that right after `exit status 1` _another_ `[go test]` is performed.

I thought it may just be improper use of the `-c` flag on my part, but even when I remove it, the output always doubles up.

![image](https://user-images.githubusercontent.com/93833532/196807083-0ead3a70-842c-4509-90ef-cc4a6812bd35.png)

Removing my editor (nvim) from the equation seems to fix the doubling up, but how would I write tests then? :joy:

![image](https://user-images.githubusercontent.com/93833532/196808972-08872822-d6a3-4582-b457-c6f704280226.png)

I'm not fully convinced it's to do with my editor as `entr` has no trouble running the command one time properly

![image](https://user-images.githubusercontent.com/93833532/196809371-decd08be-6f7a-4f59-ad89-748afdab1175.png)

If you need me to clarify anything let me know.

Cheers :beers:

**Comment by wtetsu** [comment]
Hi, thank you for your report!

In my env (On macOS Monterey),
nvim reproduces the phenomenon you reported (vim worked as expected, though)

Let me investigate more later, thank you!

**Comment by wtetsu** [comment]
Hi, probably v1.1.4 fixed the problem.

If you are a mac user, you can wait brew package release and run `brew upgrade` (it takes several days)
Or, you can download binaries here.

https://github.com/wtetsu/gaze/releases

**Comment by j-mnr** [comment]
Yup the latest release fixed it, Thanks! :smile:

![image](https://user-images.githubusercontent.com/93833532/197007044-d962637f-2d16-4d66-9f12-ca767409a175.png)
